# Generated by Django 5.2.7 on 2025-10-24 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Predio')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('superficie', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Superficie (ha)')),
                ('tipo_suelo', models.CharField(default='No especificado', max_length=100, verbose_name='Tipo de Suelo')),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Faena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Faena')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Término')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_ejecucion', 'En Ejecución'), ('suspendida', 'Suspendida'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('operario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operario Asignado')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faenas.predio', verbose_name='Predio')),
            ],
            options={
                'ordering': ['fecha_inicio', 'estado'],
            },
        ),
    ]
